name: Publish React Website to CPanel

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      # Step 2: Set up Node.js and install dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version you need

      - name: Install dependencies
        run: npm install

      # Step 3: Update Browserslist DB
      - name: Update Browserslist DB
        run: npx update-browserslist-db@latest

      # Step 4: Build the project (disable CI to allow warnings)
      - name: Build the project
        run: CI=false npm run build

      # Step 5: Deploy to FTP server
      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build  # Use the build directory generated by React
          server-dir: /public_html  # Remote directory on your server
